// Generated by https://quicktype.io

export interface Motorcycle {
  id:            number;
  status:        boolean;
  license_plate: string;
  model_id:      number;
  created_at:    string;
  updated_at:    string;
  model:         Model;
  driver?:       Driver;
}

export interface Driver {
  id:             number;
  driver_license: string;
  identity_card:  string;
  latitude:       string;
  longitude:      string;
  motorcycle_id:  number;
  status:         boolean;
  person_id:      number;
  created_at:     string;
  updated_at:     string;
  person:         Person;
}

export interface Person {
  id:         number;
  first_name: string;
  last_name:  string;
  phone:      string;
  email:      string;
  created_at: string;
  updated_at: string;
  user_id:    number;
  role:       string;
}

export interface Model {
  id:         number;
  name:       string;
  year:       string;
  brand_id:   number;
  created_at: string;
  updated_at: string;
  brand:      Brand;
}

export interface Brand {
  id:         number;
  name:       string;
  created_at: string;
  updated_at: string;
}
