// Generated by https://quicktype.io

export interface Address {
  id:          number;
  address:     string;
  latitude:    number;
  longitude:   number;
  customer_id: number;
  created_at:  string;
  updated_at:  string;
}
