// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  query:       string[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  id:            string;
  type:          string;
  place_type:    string[];
  relevance:     number;
  properties:    Properties;
  text_es:       string;
  place_name_es: string;
  text:          string;
  place_name:    string;
  center:        number[];
  geometry:      Geometry;
  context:       Context[];
  language_es?:  Language;
  language?:     Language;
}

export interface Context {
  id:          ID;
  mapbox_id:   MapboxID;
  wikidata:    Wikidata;
  text_es:     Text;
  language_es: Language;
  text:        Text;
  language:    Language;
  short_code?: ShortCode;
}

export enum ID {
  Country8734 = "country.8734",
  Place2066462 = "place.2066462",
  Region42014 = "region.42014",
}

export enum Language {
  Es = "es",
}

export enum MapboxID {
  DXJuOm1IeHBsYzpINGdl = "dXJuOm1ieHBsYzpINGdl",
  DXJuOm1IeHBsYzpJaDQ = "dXJuOm1ieHBsYzpJaDQ",
  DXJuOm1IeHBsYzpwQjQ = "dXJuOm1ieHBsYzpwQjQ",
}

export enum ShortCode {
  Bo = "bo",
  BoS = "BO-S",
}

export enum Text {
  Bolivia = "Bolivia",
  DepartamentoDeSantaCruz = "Departamento de Santa Cruz",
  SantaCruzDeLaSierra = "Santa Cruz de la Sierra",
}

export enum Wikidata {
  Q170688 = "Q170688",
  Q235106 = "Q235106",
  Q750 = "Q750",
}

export interface Geometry {
  coordinates: number[];
  type:        string;
}

export interface Properties {
  foursquare: string;
  landmark:   boolean;
  address?:   string;
  category:   string;
  wikidata?:  string;
  maki?:      string;
}
