// Generated by https://quicktype.io

import { User } from "./user.interface";

export interface RegisterUser {
  status: string;
  data:   User;
  errors?: Errors;
}

export interface Errors {
  password_confirmation: string[];
  full_messages:         string[];
}
