// Generated by https://quicktype.io

export interface RegisterDriver {
  id:         number;
  first_name: string;
  last_name:  string;
  phone:      string;
  email:      string;
  created_at: string;
  updated_at: string;
  user_id:    number;
  role:       string;
}
